# Generated by Django 6.0.7 on 2026-07-20 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Empresa del Holding')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF')),
            ],
            options={
                'verbose_name': 'Empresa del Holding',
                'verbose_name_plural': 'Empresas del Holding',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF / Identificación Fiscal')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección Fiscal')),
                ('documento_rif', models.FileField(blank=True, null=True, upload_to='documentos_proveedores/rif/', verbose_name='Copia de RIF')),
                ('acta_constitutiva', models.FileField(blank=True, null=True, upload_to='documentos_proveedores/actas/', verbose_name='Acta Constitutiva')),
                ('otros_documentos', models.FileField(blank=True, null=True, upload_to='documentos_proveedores/otros/', verbose_name='Otros Documentos')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=200, verbose_name='Nombre del Equipo / Material')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('estatus', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_STOCK', 'En Stock'), ('ASIGNADO', 'Asignado'), ('AGOTADO', 'Agotado')], default='EN_STOCK', max_length=20, verbose_name='Estatus')),
                ('serial_o_detalles', models.TextField(blank=True, verbose_name='Seriales / Observaciones del Equipo')),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('empresa_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.empresaholding', verbose_name='Empresa Asignada')),
            ],
            options={
                'verbose_name': 'Equipo / Material de Inventario',
                'verbose_name_plural': 'Inventario de Equipos y Materiales',
            },
        ),
        migrations.CreateModel(
            name='RegistroCompraPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_glpi', models.CharField(max_length=50, verbose_name='N° Ticket GLPI')),
                ('titulo_requerimiento', models.CharField(max_length=200, verbose_name='Título / Asunto del Requerimiento')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares ($)'), ('VES', 'Bolívares (Bs.)'), ('EUR', 'Euros (€)'), ('USDT', 'USDT / Cripto'), ('OTRO', 'Otro Pago')], default='USD', max_length=10, verbose_name='Moneda de Pago')),
                ('estatus', models.CharField(choices=[('COTIZANDO', 'En Cotización'), ('COMPRADO', 'Comprado / Adjudicado'), ('TRANSITO', 'En Tránsito / Almacén'), ('ASIGNADO', 'Asignado a Empresa del Holding')], default='COMPRADO', max_length=20, verbose_name='Estatus')),
                ('desglose_items', models.TextField(help_text='Escriba o pegue libremente la lista de materiales aquí.', verbose_name='Desglose de Ítems / Lista de Materiales Solicitados')),
                ('monto_cot_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Cotización 1')),
                ('archivo_cot_1', models.FileField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='PDF Cotización 1')),
                ('monto_cot_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Cotización 2')),
                ('archivo_cot_2', models.FileField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='PDF Cotización 2')),
                ('monto_cot_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Cotización 3')),
                ('archivo_cot_3', models.FileField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='PDF Cotización 3')),
                ('notas', models.TextField(blank=True, verbose_name='Notas / Observaciones Generales')),
                ('empresa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresaholding', verbose_name='Empresa del Holding Asignada')),
                ('proveedor_cot_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_cot_1', to='gestion.proveedor', verbose_name='Proveedor Cotización 1')),
                ('proveedor_cot_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_cot_2', to='gestion.proveedor', verbose_name='Proveedor Cotización 2')),
                ('proveedor_cot_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_cot_3', to='gestion.proveedor', verbose_name='Proveedor Cotización 3')),
            ],
            options={
                'verbose_name': 'Solicitud / Ticket de Compra',
                'verbose_name_plural': 'Solicitudes / Tickets de Compras',
            },
        ),
        migrations.CreateModel(
            name='PagoProveedorAdjudicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('factura', models.FileField(blank=True, null=True, upload_to='facturas_compras/', verbose_name='Factura (PDF/Imagen)')),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_pago/', verbose_name='Comprobante de Pago (PDF/Imagen)')),
                ('descripcion_adjudicacion', models.CharField(blank=True, max_length=255, verbose_name='¿Qué se le compró a este proveedor?')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedor', verbose_name='Proveedor Adjudicado')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_proveedores', to='gestion.registrocomprapago')),
            ],
        ),
    ]
