# Generated by Django 6.0.7 on 2026-07-22 13:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocomprapago',
            name='notas',
        ),
        migrations.AlterField(
            model_name='registrocomprapago',
            name='desglose_items',
            field=models.TextField(verbose_name='Desglose de Ítems / Lista de Materiales Solicitados'),
        ),
        migrations.CreateModel(
            name='HistoricalEmpresaHolding',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Empresa del Holding')),
                ('rif', models.CharField(db_index=True, max_length=20, verbose_name='RIF')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Empresa del Holding',
                'verbose_name_plural': 'historical Empresas del Holding',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInventario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=200, verbose_name='Nombre del Equipo / Material')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('estatus', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_STOCK', 'En Stock'), ('ASIGNADO', 'Asignado'), ('AGOTADO', 'Agotado')], default='EN_STOCK', max_length=20, verbose_name='Estatus')),
                ('serial_o_detalles', models.TextField(blank=True, verbose_name='Seriales / Observaciones del Equipo')),
                ('actualizado_el', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa_asignada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.empresaholding', verbose_name='Empresa Asignada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Equipo / Material de Inventario',
                'verbose_name_plural': 'historical Inventario de Equipos y Materiales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPagoProveedorAdjudicado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('factura', models.TextField(blank=True, max_length=100, null=True, verbose_name='Factura (PDF/Imagen)')),
                ('comprobante_pago', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comprobante de Pago (PDF/Imagen)')),
                ('descripcion_adjudicacion', models.CharField(blank=True, max_length=255, verbose_name='¿Qué se le compró a este proveedor?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.proveedor', verbose_name='Proveedor Adjudicado')),
                ('solicitud', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.registrocomprapago')),
            ],
            options={
                'verbose_name': 'historical pago proveedor adjudicado',
                'verbose_name_plural': 'historical pago proveedor adjudicados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProveedor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('rif', models.CharField(db_index=True, max_length=20, verbose_name='RIF / Identificación Fiscal')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección Fiscal')),
                ('documento_rif', models.TextField(blank=True, max_length=100, null=True, verbose_name='Copia de RIF')),
                ('acta_constitutiva', models.TextField(blank=True, max_length=100, null=True, verbose_name='Acta Constitutiva')),
                ('otros_documentos', models.TextField(blank=True, max_length=100, null=True, verbose_name='Otros Documentos')),
                ('creado_el', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Proveedor',
                'verbose_name_plural': 'historical Proveedores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRegistroCompraPago',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ticket_glpi', models.CharField(max_length=50, verbose_name='N° Ticket GLPI')),
                ('titulo_requerimiento', models.CharField(max_length=200, verbose_name='Título / Asunto del Requerimiento')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares ($)'), ('VES', 'Bolívares (Bs.)'), ('EUR', 'Euros (€)'), ('USDT', 'USDT / Cripto'), ('OTRO', 'Otro Pago')], default='USD', max_length=10, verbose_name='Moneda de Pago')),
                ('estatus', models.CharField(choices=[('COTIZANDO', 'En Cotización'), ('COMPRADO', 'Comprado / Adjudicado'), ('TRANSITO', 'En Tránsito / Almacén'), ('ASIGNADO', 'Asignado a Empresa del Holding')], default='COMPRADO', max_length=20, verbose_name='Estatus')),
                ('desglose_items', models.TextField(verbose_name='Desglose de Ítems / Lista de Materiales Solicitados')),
                ('monto_cot_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Cotización 1')),
                ('archivo_cot_1', models.TextField(blank=True, max_length=100, null=True, verbose_name='PDF Cotización 1')),
                ('monto_cot_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Cotización 2')),
                ('archivo_cot_2', models.TextField(blank=True, max_length=100, null=True, verbose_name='PDF Cotización 2')),
                ('monto_cot_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Cotización 3')),
                ('archivo_cot_3', models.TextField(blank=True, max_length=100, null=True, verbose_name='PDF Cotización 3')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa_destino', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.empresaholding', verbose_name='Empresa del Holding Asignada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor_cot_1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.proveedor', verbose_name='Proveedor Cotización 1')),
                ('proveedor_cot_2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.proveedor', verbose_name='Proveedor Cotización 2')),
                ('proveedor_cot_3', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.proveedor', verbose_name='Proveedor Cotización 3')),
            ],
            options={
                'verbose_name': 'historical Solicitud / Ticket de Compra',
                'verbose_name_plural': 'historical Solicitudes / Tickets de Compras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
