# Generated by Django 6.0.7 on 2026-07-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_registrocomprapago_notas_and_more'),
    ]

    operations = [
    ]
