# Generated by Django 6.0.7 on 2026-07-25 19:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_add_perfil_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventario',
            name='nombre_equipo',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='nombre_equipo',
        ),
        migrations.AddField(
            model_name='historicalinventario',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Unitario Base ($)'),
        ),
        migrations.AddField(
            model_name='historicalinventario',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AddField(
            model_name='historicalinventario',
            name='producto_marca_modelo',
            field=models.CharField(default='', max_length=250, verbose_name='Producto - Marca y Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='historicalinventario',
            name='tipo_iva',
            field=models.CharField(choices=[('CON_IVA', 'Con IVA (16%)'), ('SIN_IVA', 'Exento / Sin IVA')], default='CON_IVA', max_length=10, verbose_name='Condición de IVA'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='historicalregistrocomprapago',
            name='solicitante_info',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona que Solicitó / Email'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Unitario Base ($)'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto_marca_modelo',
            field=models.CharField(default='', max_length=250, verbose_name='Producto - Marca y Modelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo_iva',
            field=models.CharField(choices=[('CON_IVA', 'Con IVA (16%)'), ('SIN_IVA', 'Exento / Sin IVA')], default='CON_IVA', max_length=10, verbose_name='Condición de IVA'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='registrocomprapago',
            name='solicitante_info',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona que Solicitó / Email'),
        ),
        migrations.AlterField(
            model_name='historicalinventario',
            name='serial_o_detalles',
            field=models.TextField(blank=True, verbose_name='Seriales / Observaciones'),
        ),
        migrations.AlterField(
            model_name='historicalpagoproveedoradjudicado',
            name='descripcion_adjudicacion',
            field=models.TextField(blank=True, null=True, verbose_name='Desglose por Línea (Ítem | Marca | Serial | Costo)'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='serial_o_detalles',
            field=models.TextField(blank=True, verbose_name='Seriales / Observaciones'),
        ),
        migrations.AlterField(
            model_name='pagoproveedoradjudicado',
            name='descripcion_adjudicacion',
            field=models.TextField(blank=True, null=True, verbose_name='Desglose por Línea (Ítem | Marca | Serial | Costo)'),
        ),
        migrations.CreateModel(
            name='HistoricalRequerimientoTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ticket_glpi', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Ticket GLPI (Opcional)')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / Asunto del Requerimiento')),
                ('desglose_items', models.TextField(verbose_name='Lista / Desglose de Materiales Solicitados')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente por Revisar'), ('EN_CURSO', 'En Cotización / En Curso'), ('PROCESADO', 'Procesado / Comprado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estatus')),
                ('creado_el', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa_holding', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.empresaholding', verbose_name='Empresa del Holding')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'historical Requerimiento / Ticket',
                'verbose_name_plural': 'historical Requerimientos / Tickets Solicitados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador Global'), ('COMPRAS', 'Analista de Compras'), ('SOLICITANTE', 'Usuario Solicitante')], default='SOLICITANTE', max_length=20, verbose_name='Rol en el Sistema')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequerimientoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_glpi', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Ticket GLPI (Opcional)')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / Asunto del Requerimiento')),
                ('desglose_items', models.TextField(verbose_name='Lista / Desglose de Materiales Solicitados')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente por Revisar'), ('EN_CURSO', 'En Cotización / En Curso'), ('PROCESADO', 'Procesado / Comprado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estatus')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empresa_holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresaholding', verbose_name='Empresa del Holding')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Requerimiento / Ticket',
                'verbose_name_plural': 'Requerimientos / Tickets Solicitados',
            },
        ),
        migrations.AddField(
            model_name='historicalregistrocomprapago',
            name='requerimiento_origen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.requerimientoticket', verbose_name='Requerimiento en Curso Seleccionado'),
        ),
        migrations.AddField(
            model_name='registrocomprapago',
            name='requerimiento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_asociadas', to='gestion.requerimientoticket', verbose_name='Requerimiento en Curso Seleccionado'),
        ),
    ]
