# Generated by Django 6.0.7 on 2026-07-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_add_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompraInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_item', models.CharField(max_length=255, verbose_name='Ítem / Producto')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial / N° Serie')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Unitario ($)')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_inventario', to='gestion.registrocomprapago', verbose_name='Compra / Pago')),
            ],
            options={
                'verbose_name': 'Ítem para Inventario',
                'verbose_name_plural': 'Ítems para Inventario (Marca, Serial y Costo)',
            },
        ),
    ]
