# Generated by Django 6.0.7 on 2026-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_itemcomprainventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistrocomprapago',
            name='fecha_registro',
            field=models.DateField(verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='historicalregistrocomprapago',
            name='ticket_glpi',
            field=models.CharField(max_length=50, verbose_name='N° Ticket'),
        ),
        migrations.AlterField(
            model_name='registrocomprapago',
            name='fecha_registro',
            field=models.DateField(verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='registrocomprapago',
            name='ticket_glpi',
            field=models.CharField(max_length=50, verbose_name='N° Ticket'),
        ),
    ]
