# Generated by Django 6.0.7 on 2026-07-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_historicalregistrocomprapago_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='rubro',
            field=models.CharField(choices=[('Tecnología / Informática', 'Tecnología / Informática'), ('Ferretería / Materiales de Construcción', 'Ferretería / Materiales de Construcción'), ('Papelería / Material de Oficina', 'Papelería / Material de Oficina'), ('Mobiliario y Equipamiento', 'Mobiliario y Equipamiento'), ('Servicios Generales / Mantenimiento', 'Servicios Generales / Mantenimiento'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Seguridad / Vigilancia', 'Seguridad / Vigilancia'), ('Limpieza y Aseo', 'Limpieza y Aseo'), ('Transporte / Logística', 'Transporte / Logística'), ('Otro / General', 'Otro / General')], default='Otro / General', max_length=100, verbose_name='Rubro / Tipo de Servicio'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(choices=[('Tecnología / Informática', 'Tecnología / Informática'), ('Ferretería / Materiales de Construcción', 'Ferretería / Materiales de Construcción'), ('Papelería / Material de Oficina', 'Papelería / Material de Oficina'), ('Mobiliario y Equipamiento', 'Mobiliario y Equipamiento'), ('Servicios Generales / Mantenimiento', 'Servicios Generales / Mantenimiento'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Seguridad / Vigilancia', 'Seguridad / Vigilancia'), ('Limpieza y Aseo', 'Limpieza y Aseo'), ('Transporte / Logística', 'Transporte / Logística'), ('Otro / General', 'Otro / General')], default='Otro / General', max_length=100, verbose_name='Rubro / Tipo de Servicio'),
        ),
    ]
