# Generated by Django 6.0.7 on 2026-07-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_historicalproveedor_rubro_proveedor_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventario',
            name='empresa_origen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.empresaholding', verbose_name='Empresa Origen'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='acta_constitutiva_verificada',
            field=models.BooleanField(default=False, verbose_name='Acta constitutiva verificada'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='direccion_verificada',
            field=models.BooleanField(default=False, verbose_name='Dirección verificada'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='documento_rif_verificado',
            field=models.BooleanField(default=False, verbose_name='Copia de RIF verificada'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Correo electrónico verificado'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='nombre_empresa_verificado',
            field=models.BooleanField(default=False, verbose_name='Nombre de la empresa verificado'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='rif_verificado',
            field=models.BooleanField(default=False, verbose_name='RIF verificado'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='telefono_verificado',
            field=models.BooleanField(default=False, verbose_name='Teléfono verificado'),
        ),
        migrations.AddField(
            model_name='historicalproveedor',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Proveedor verificado'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='empresa_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_origen', to='gestion.empresaholding', verbose_name='Empresa Origen'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='acta_constitutiva_verificada',
            field=models.BooleanField(default=False, verbose_name='Acta constitutiva verificada'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion_verificada',
            field=models.BooleanField(default=False, verbose_name='Dirección verificada'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='documento_rif_verificado',
            field=models.BooleanField(default=False, verbose_name='Copia de RIF verificada'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Correo electrónico verificado'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_empresa_verificado',
            field=models.BooleanField(default=False, verbose_name='Nombre de la empresa verificado'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rif_verificado',
            field=models.BooleanField(default=False, verbose_name='RIF verificado'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_verificado',
            field=models.BooleanField(default=False, verbose_name='Teléfono verificado'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Proveedor verificado'),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='rubro',
            field=models.CharField(choices=[('Tecnologia / Informática', 'Tecnología / Informática'), ('Ferretería / Materiales de Construcción', 'Ferretería / Materiales de Construcción'), ('Papelería / Material de Oficina', 'Papelería / Material de Oficina'), ('Mobiliario y Equipamiento', 'Mobiliario y Equipamiento'), ('Servicios Generales / Mantenimiento', 'Servicios Generales / Mantenimiento'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Seguridad / Vigilancia', 'Seguridad / Vigilancia'), ('Limpieza y Aseo', 'Limpieza y Aseo'), ('Transporte / Logística', 'Transporte / Logística'), ('Otro / General', 'Otro / General')], default='Otro / General', max_length=100, verbose_name='Rubro / Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(choices=[('Tecnologia / Informática', 'Tecnología / Informática'), ('Ferretería / Materiales de Construcción', 'Ferretería / Materiales de Construcción'), ('Papelería / Material de Oficina', 'Papelería / Material de Oficina'), ('Mobiliario y Equipamiento', 'Mobiliario y Equipamiento'), ('Servicios Generales / Mantenimiento', 'Servicios Generales / Mantenimiento'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Seguridad / Vigilancia', 'Seguridad / Vigilancia'), ('Limpieza y Aseo', 'Limpieza y Aseo'), ('Transporte / Logística', 'Transporte / Logística'), ('Otro / General', 'Otro / General')], default='Otro / General', max_length=100, verbose_name='Rubro / Tipo de Servicio'),
        ),
    ]
